export * from './footer';
export * from './header';
export * from './maxWidth';
export * from './mySideBar';
export * from './myTitle';
export * from './region';
export * from './mySearch';
export * from './myList';
export * from './pagination';
